# path or the data directory
# Here there must be chr in format chr{number}.ready.vcf.gz
samples: 'data'

# path to the results directory
outdir: 'results'

# path to the logs directory
logdir: 'logs'

# Chr we wanna run
chr: 'chr24'

parameters:
    paste_header:
        header: "resources/chr.header.txt"
    
    make_long:
        infos: "AF DP AN AC"
        formats: "GT AD DP GQ"
        preHeader: "ID"


resources:
    default:
        threads: 1
        mem:  4096
        walltime: 10

    make_long:
        threads: 8
        mem:  4096
        walltime: 120
