# path or the data directory
# Here there must be chr in format chr{number}.ready.vcf.gz
samples: 'data'

# path to the results directory
outdir: 'results'

# path to the logs directory
logdir: 'logs'

# Chrs we wanna run
chr_list: ["chr22", "chr23"]

parameters:
    paste_header:
        header_vcf: "resources/chr.header.txt"
    
    make_long:
        infos: "AF DP AN AC"
        formats: "GT AD DP GQ"
        preHeader: "ID"

    join_files:
        header_tsv: "resources/tsv.header.tsv"


resources:
    default:
        threads: 1
        mem:  4096
        walltime: 40

    remove_vcf_header:
        threads: 1
        mem:  12288
        walltime: 80
    
    split_chr:
        threads: 1
        mem:  12288
        walltime: 180

    make_long:
        threads: 8
        mem:  24576
        walltime: 120
