$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
    samples:
        type: string
    outdir: 
        type: string
    logdir: 
        type: string
    chr_list:
        type: array


    parameters:
        properties:
            paste_header:
                type: object
                properties:
                    header_vcf:
                        type: string

            make_long:
                type: object
                properties:
                    infos:
                        type: string
                    formats:
                        type: string
                    preHeader:
                        type: string

            join_files:
                type: object
                properties:
                    header_tsv:
                        type: string

    
    resources:
        properties:
            default:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer

            make_long:
                type: object
                properties:
                    threads:
                        type: integer
                    mem:
                        type: integer
                    walltime:
                        type: integer
